name: CI/CD Pipeline com Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t seu-app:${{ github.sha }} .

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag and Push to Amazon ECR
      run: |
        docker tag seu-app:${{ github.sha }} $AWS_ECR_REGISTRY/seu-app:${{ github.sha }}
        docker push $AWS_ECR_REGISTRY/seu-app:${{ github.sha }}

    - name: Deploy to AWS ECS
      run: |
         env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'sua-região-aws'  # Exemplo: us-west-2

